### ISSUE TITLE
Create logical models for workflow data

### ISSUE THREAD

**Issue by pmanko** [I-TECH-UW/emr-lis-ig#5]

**Comment by pmanko** [comment]
We should base this on a generic representation of the Lab workflow data, which can be similar to https://b-techbw.github.io/bw-lab-ig/StructureDefinition-BwLabDataDictionary.html

**Comment by pmanko** [comment]
@mozzy11 this would be a useful issue to close. A full logical model would facilitate discussions about the communication.

**Comment by mozzy11** [comment]
Oh sure , let me work on this next

**Comment by mozzy11** [comment]
HI @pmanko 
For the [Systems ](https://github.com/I-TECH-UW/emr-lis-ig/blob/main/input/fsh/emr-lis-logical-model.fsh#L20-L23)to map ,
i can see you added both OpenMRS (RefApp 2.9) and Isanteplus (iSantePlus 2)
That looks to me like a dupication , 
Any reason why you added the two Systems ??

**Comment by mozzy11** [comment]
Was thinking of how to get the OpenELIS-FHIR mappings ,
but it seems OpenELIS runs a instance of HAPI-FHIR server where all the FHIR requests are forwarded.
so in this case ,  in the Logical model mappings , can we take the HAPI-FHIR server Data model as the  OpenELIS data model ??

**Comment by pmanko** [comment]
> HI @pmanko
> For the [Systems ](https://github.com/I-TECH-UW/emr-lis-ig/blob/main/input/fsh/emr-lis-logical-model.fsh#L20-L23)to map ,
> i can see you added both OpenMRS (RefApp 2.9) and Isanteplus (iSantePlus 2)
> That looks to me like a dupication ,
> Any reason why you added the two Systems ??

I think we can just focus on the FHIR and OpenMRS mappings currently. This would also be a good place to include mappings into OpenELIS in terms of how the concepts map directly to the OpenELIS data model, not the adjacent Hapi server.

**Comment by pmanko** [comment]
But in general, we first need a logical model that clearly maps to the Profiles that we described - the other mappings are implementation-specific. Also, you can just put placeholders for mappings for the other systems for this issue, since #6 covers the mapping part for OpenMRS, and we can add specific issues for other systems.

**Comment by pmanko** [comment]
> HI @pmanko
> For the [Systems ](https://github.com/I-TECH-UW/emr-lis-ig/blob/main/input/fsh/emr-lis-logical-model.fsh#L20-L23)to map ,
> i can see you added both OpenMRS (RefApp 2.9) and Isanteplus (iSantePlus 2)
> That looks to me like a dupication ,
> Any reason why you added the two Systems ??

iSantePlus represents Lab Orders using the `Obs` table, so the mappings would be different between the two.

**Comment by mozzy11** [comment]
Hi @pmanko ,
how should i determine the elements to include in the Logical Model mappings ??
i currently look at the OpenMRS FHIR [wiki](https://wiki.openmrs.org/display/projects/Mapped+FHIR+Resources).
and only add mappings for the elements that were mapped in the FHIR2 module

**Comment by mozzy11** [comment]
WIP https://github.com/I-TECH-UW/emr-lis-ig/pull/15
