### ISSUE TITLE
Create example FHIR resources

### ISSUE THREAD

**Issue by pmanko** [I-TECH-UW/emr-lis-ig#8]
- [ ] Composition
- [ ] Task
- [ ] ServiceRequest
- [ ] DiagnosticReport
- [ ] Observation
- [ ] Full Lab Order Bundle (https://github.com/B-TECHBW/bw-lab-ig/blob/93a327a392a3238cb174b9e19d6c6855e329df81/input/fsh/bw-lab-Examples.fsh#L108)

**Comment by pmanko** [comment]
Some examples can be found here: 
- https://wiki.openmrs.org/display/projects/Lab+Integration+Workflow
- http://docs.openelis-global.org/en/latest/messages.html

**Comment by mozzy11** [comment]
hi @pmanko , am starting to work on this issue. you can actually grant me priviledges to assign my self an issue.
are these the only example resources we would want ??
 Composition
 Task
 ServiceRequest
 DiagnosticReport
 Observation
 Full Lab Order Bundle

**Comment by mozzy11** [comment]
hi @pmanko ,see PR
https://github.com/I-TECH-UW/emr-lis-ig/pull/12

**Comment by pmanko** [comment]
Thanks @mozzy11 !

https://i-tech-uw.github.io/emr-lis-ig/artifacts.html#example-example-instances
